VisitOnline/Controllers/PanelController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using VisitOnline.Database.Tabels;
using VisitOnline.Models;
using VisitOnline.Services;
using Microsoft.AspNetCore.Http;
using System.IO;
using Microsoft.AspNetCore.Hosting;
using System.Drawing;
using System.Drawing.Imaging;

namespace VisitOnline.Controllers
{
    public class PanelController : Controller
    {
        private IUser user;
        private IHostingEnvironment hostingEnv;
        public PanelController(IUser _user, IHostingEnvironment env)
        {
            user = _user;
            this.hostingEnv = env;
        }

        public IActionResult DocDashboard()
        {
            string currentuser = User.Identity.Name;
            string status = user.GetUserStatus(currentuser);

            switch (status)
            {
                case "disable":
                    
                    ViewBag.Status = "disable";
                    break;
                case "enable":
                    ViewBag.Status = "enable";
                    break;
                case "waiting":
                    ViewBag.Status = "waiting";
                    break;
            }
          
            
            
            Doctor users = user.GetDoctor(currentuser);
            DoctorViewModel doctor = new DoctorViewModel()
            {
                Mobile = users.User.Mobile,
                AddressMatab = users.AddressMatab,
                Description = users.Description,
                MeliCode = users.MeliCode,
                NameFamily = users.User.NameFamily,
                DoctorId = users.DoctorId,
                Rate = users.Rate,
                SNP = users.SNP,
                Takhasos = users.Takhasos,
                TelMatab = users.TelMatab
            };

            
            return View(doctor);
        }

        public IActionResult CompleteInformation()
        {
            ViewBag.ComOk = false;
            string currentuser = User.Identity.Name;
            Doctor users = user.GetDoctor(currentuser);

            DoctorViewModel doctor = new DoctorViewModel()
            {
               
                AddressMatab = users.AddressMatab,
                Description = users.Description,
                MeliCode = users.MeliCode,
                NameFamily = users.User.NameFamily,
                DoctorId = users.DoctorId,
                Rate = users.Rate,
                SNP = users.SNP,
                Takhasos = users.Takhasos,
                TelMatab = users.TelMatab
            };
            return View(doctor);
        }
        [HttpPost]

        public IActionResult CompleteInformation(DoctorViewModel models)
        {
            if (ModelState.IsValid)
            {

                string currentuser = User.Identity.Name;
                user.UpdateDoctor (models , currentuser);

                if (models.File != null)
                {
                    var FileDic = $"Cert\\{currentuser}";

                    string FilePath = Path.Combine(hostingEnv.WebRootPath, FileDic);

                    if (!Directory.Exists(FilePath))

                        Directory.CreateDirectory(FilePath);

                    var fileName = models.File.FileName;
                    string getFormat = fileName.Split(".")[1];
                    string newFilename = models.SNP + "." + getFormat;
                    var filePath = Path.Combine(FilePath, newFilename);



                    using (FileStream fs = System.IO.File.Create(filePath))

                    {

                        models.File.CopyTo(fs);

                    }
                }
                else
                {
                    return BadRequest();
                }
               


            }
            ViewBag.ComOk = true;
            return View(models);
        }

        public IActionResult SickDashboard()
        {
            string currentuser = User.Identity.Name;
           

            Sick users = user.GetSick(currentuser);
            SickviewModels bimar = new SickviewModels()
            {
                Mobile = users.User.Mobile,
                NameFamily = users.User.NameFamily,
                province = users.province,
                Address = users.Address ,
                Age = users.Age ,
                City = users.City,
                Region = users.Region
            };


            return View(bimar);
        }

        public IActionResult SickInformation()
        {

            string currentuser = User.Identity.Name;
            Sick users = user.GetSick(currentuser);
            SickviewModels sick = new SickviewModels()
            {
                Mobile = users.User.Mobile,
                NameFamily = users.User.NameFamily,
                province = users.province,
                Address = users.Address,
                Region = users.Region ,
                City = users.City ,
                Age =users.Age ,
                
            };
            return View(sick);
        }
        [HttpPost]
        public IActionResult SickInformation(SickviewModels model)
        {
            if (ModelState.IsValid)
            {
                string currentuser = User.Identity.Name;
                user.UpdateSick(model , currentuser);

            }
            return View(model);
        }

        public IActionResult SeeVisit()
        {
            List<VisitRequest> ListVisit = user.GetVisitList();
            return View(ListVisit);
        }
        public RequestVisitModel VisitData(int id)
        {
            string cuser = User.Identity.Name;
            RequestVisitModel visitModel = user.GetRequsetDataSick(id, cuser);
           
            return visitModel;

        }

        public bool DelReqSic(int id)
        {

            return user.DeleteReqSic(id);
        }
        public RequestVisitModel VisitForDocData(int id)
        {
            string cuser = User.Identity.Name;
            RequestVisitModel visitModel = user.GetRequsetDataDoc(id, cuser);

            return visitModel;
        }


        public IActionResult RequestVisit()
        {

            return View();
        }

        [HttpPost]
        public IActionResult RequestVisit(RequestVisitModel model)
        {
           
            string cuser = User.Identity.Name;
            user.AddRequsetVisit(model, cuser);

            
            return View();
        }

        public List<DoctorViewModel> GetDoctor(int id)
        {

            return user.GetListDoctor(id); 
        }


        public IActionResult SeeReViDoc()
        {
            string cuser = User.Identity.Name;
           List<RequestVisitModel> visitModels = user.GetListReViDoc(cuser);
            return View(visitModels);
        }

      

        [HttpPost]
        public bool AnswerViDoc(RequestVisitModel model)
        {
            

            string cuser = User.Identity.Name;
            user.UpdateRequsetVisit(model, cuser);

            return true;
        }





    }
}

VisitOnline/Views/Panel/CompleteInformation.cshtml
@model VisitOnline.Models.DoctorViewModel
@{
    ViewData["Title"] = "CompleteInformation";
    Layout = "~/Views/Shared/_PanelDoctorLayout.cshtml";
}

 
 
    <div class="col-xl-9 col-lg-8 col-md-7 p-2">
        <div class="card border-0 rounded-custom-2 shadow-sm p-3 h-100">
            @if (ViewBag.ComOk)
            {
                <div class="alert alert-success" id="success-alert">
                    <button type="button" class="close" data-dismiss="alert">x</button>
                    اطلاعات شما با موفقیت ارسال شد
                </div>
            }

            <div class="col-sm-12 p-2">
                <p class="h2 ismb text-b d-flex align-items-center justify-content-between">
                    تکمیل اطلاعات
                    <i class="bi bi-pen"></i>
                </p>
                <hr class="my-2">
            </div>
            <div class="py-3">
                <div class="col-xxl-10 m-auto p-1">
                    @using (Html.BeginForm("CompleteInformation", "Panel", FormMethod.Post, new { enctype = "multipart/form-data" }))

                    {
                        <div class="row w-100 m-0">
                            <div class="col-12 px-2 pb-4">
                                <div class="pro-photo">
                                    <div class="small-12 medium-2 large-2 columns max-content mx-auto position-relative">
                                        <div class="circle mx-auto">
                                            <img class="profile-pic rounded-circle" src="~/img/download.jpg">
                                        </div>
                                        <div class="p-image">
                                            <i class="bi bi-camera upload-button"></i>
                                            <input class="file-upload" type="file" accept="image/*" />
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="col-lg-6 col-md-12 col-sm-6 p-2">
                                <div class="">
                                    <label for="input1" class="form-label" asp-for="NameFamily">
                                        نام و نام خانوادگی
                                    </label>
                                    <input type="text" asp-for="NameFamily" class="form-control rounded-custom-2 text-start" id="input1" value="@Model.NameFamily" placeholder="نام و نام خانوادگی خود را بنویسید">
                                    <span asp-validation-for="NameFamily" class="text-danger"></span>
                                </div>
                            </div>
                            <div class="col-lg-6 col-md-12 col-sm-6 p-2">
                                <div class="">
                                    <label for="input2" class="form-label" asp-for="MeliCode">
                                        کد ملی
                                    </label>
                                    <input type="text" asp-for="MeliCode" class="form-control rounded-custom-2 text-start" id="input12" placeholder="کد ملی ۱۰ رقمی خود را بنویسید">
                                    <span asp-validation-for="MeliCode" class="text-danger"></span>
                                </div>
                            </div>
                            <div class="col-lg-6 col-md-12 col-sm-6 p-2">
                                <div class="form-outline">
                                    <label for="input2" class="form-label" asp-for="TelMatab">
                                        تلفن مطب
                                    </label>
                                    <input type="tel" asp-for="TelMatab" class="form-control rounded-custom-2 text-start" id="input12" placeholder=" با پیش شماره شهری خود وارد کنید">
                                    <span asp-validation-for="TelMatab" class="text-danger"></span>
                                </div>
                            </div>
                            <div class="col-lg-6 col-md-12 col-sm-6 p-2">
                                <div class="">
                                    <label for="input2" class="form-label" asp-for="Mobile">
                                        شماره همراه
                                    </label>
                                    <input type="tel" asp-for="Mobile" class="form-control rounded-custom-2 text-start" id="input12" placeholder="@User.Identity.Name" value="@Model.Mobile" disabled>
                                    <span asp-validation-for="Mobile" class="text-danger"></span>
                                </div>
                            </div>
                            <div class="col-lg-6 col-md-12 col-sm-6 p-2">
                                <div class="">
                                    <label for="input12" class="form-label" asp-for="AddressMatab">
                                        آدرس مطب
                                    </label>
                                    <textarea class="form-control" asp-for="AddressMatab" id="input12" rows="3"></textarea>
                                    <span asp-validation-for="AddressMatab" class="text-danger"></span>
                                </div>
                            </div>
                            <div class="col-lg-6 col-md-12 col-sm-6 p-2">

                                <div class="">
                                    <label for="input22" class="form-label" asp-for="Description">
                                        توضیحات درباره خود
                                    </label>
                                    <textarea class="form-control" asp-for="Description" id="input22" rows="3"></textarea>
                                    <span asp-validation-for="Description" class="text-danger"></span>
                                </div>
                            </div>
                            <div class="col-lg-6 col-md-12 col-sm-6 p-2">

                                <select class="form-select form-select-sm" asp-for="Takhasos" aria-label=".form-select-sm example">
                                    <option selected>تخصص</option>
                                    <option value="1">ارتوپد </option>
                                    <option value="2">قلب عروق</option>
                                    <option value="3">مغز اعصاب</option>
                                    <option value="4">بیماری های عفونی</option>
                                    <option value="5">پوست و مو</option>
                                    <option value="6">چشم</option>
                                    <option value="7">گوش و حلق و بینی</option>
                                    <option value="8">گوارش</option>
                                    <option value="9">تغذیه</option>
                                </select>
                                <span asp-validation-for="Takhasos" class="text-danger"></span>
                            </div>



                            <div class="col-lg-6 col-md-12 col-sm-6 p-2">
                                <div class="">
                                    <label for="input2" class="form-label" asp-for="SNP">
                                        شماره نظام پزشکی
                                    </label>
                                    <input type="number" asp-for="SNP" class="form-control rounded-custom-2 text-start" id="input12" placeholder="تخصص خود را بنویسید">
                                </div>
                                <span asp-validation-for="SNP" class="text-danger"></span>
                            </div>
                            <div class="col-lg-6 col-md-12 col-sm-6 p-2">
                                <div class="">
                                    <label for="input2" class="form-label" asp-for="Certificate">
                                        آپلود جواز پزشکی
                                    </label>
                                    <input type="file" asp-for="File" name="file" class="form-control rounded-custom-2" id="inputGroupFile01" onchange="imageConvert(this)">
                                    <span asp-validation-for="Certificate" class="text-danger"></span>
                                </div>
                            </div>
                            <div class="col-lg-6 col-md-12 col-sm-6 p-2">

                            </div>
                            <div class="col-lg-6 col-md-12 col-sm-6 ms-auto p-2" style="display:none;visibility:hidden">
                                <input type="text" class="btn btn-success w-100 rounded-custom-2" id="cert" asp-for="Certificate" value="" />


                            </div>
                            <div class="col-lg-6 col-md-12 col-sm-6 ms-auto p-2">
                                <input type="submit" class="btn btn-success w-100 rounded-custom-2" id="myWish" value="ثبت اطلاعات" />


                            </div>
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>
    @section Scripts
{
        <script>
            $(document).ready(function () {

                   $("#success-alert").hide();
                   
                   $("#myWish").click(function showAlert() {
                        $("#success-alert").fadeTo(6000, 500).slideUp(500, function() {
                            $("#success-alert").slideUp(500);
                        });
                       
                  });
                });
        </script>
 }

VisitOnline/Views/Panel/DocDashboard.cshtml
@model VisitOnline.Models.DoctorViewModel
@{
    ViewData["Title"] = "DocDashboard";
    Layout = "~/Views/Shared/_PanelDoctorLayout.cshtml";
}

<div class="col-xl-9 col-lg-8 col-md-7 p-2">
    <div class="card border-0 rounded-custom-2 shadow-sm p-3 h-100">
        <div class="col-sm-12 p-2">
            <p class="h2 ismb text-b d-flex align-items-center justify-content-between">
                داشبورد
                <i class="bi bi-speedometer2"></i>
            </p>
            <hr class="my-2">
        </div>
        <div class="py-3">
            <div class="col-xxl-10 m-auto p-1">
                <div class="row w-100 m-0">
                    <div class="col-lg-6 col-md-12 col-sm-6 p-3 border">
                        <p class="h6 text-secondary d-flex align-items-center justify-content-between m-0">
                            نام و نام خانوادگی :
                            <span class="text-dark fw-bolder">
                                @Model.NameFamily
                            </span>
                        </p>
                    </div>
                    <div class="col-lg-6 col-md-12 col-sm-6 p-3 border">
                        <p class="h6 text-secondary d-flex align-items-center justify-content-between m-0">
                            شماره همراه :
                            <span class="text-dark fw-bolder">
                                @Model.Mobile
                            </span>
                        </p>
                    </div>
                    <div class="col-lg-6 col-md-12 col-sm-6 p-3 border">
                        <p class="h6 text-secondary d-flex align-items-center justify-content-between m-0">
                            کد ملی :
                            <span class="text-dark fw-bolder">
                                @Model.MeliCode
                            </span>
                        </p>
                    </div>
                    <div class="col-lg-6 col-md-12 col-sm-6 p-3 border">
                        <p class="h6 text-secondary d-flex align-items-center justify-content-between m-0">
                            تخصص :
                            <span class="text-dark fw-bolder">
                               @Model.Takhasos
                            </span>
                        </p>
                    </div>
                    <div class="col-lg-6 col-md-12 col-sm-6 p-3 border">
                        <p class="h6 text-secondary d-flex align-items-center justify-content-between m-0">
                            شماره نظام پزشکی :
                            <span class="text-dark fw-bolder">
                                @Model.SNP
                            </span>
                        </p>
                    </div>
                    @*<div class="col-lg-6 col-md-12 col-sm-6 p-3 border">
                        <p class="h6 text-secondary d-flex align-items-center justify-content-between m-0">
                            رمز عبور :
                            <span class="text-dark fw-bolder">
                                
                            </span>
                        </p>
                    </div>*@
                    <div class="col-12 p-3 border">
                        <p class="h6 text-secondary m-0">
                            آدرس مطب :
                            <span class="text-dark fw-bolder">
                                @Model.AddressMatab
                            </span>
                        </p>
                    </div>
                    @*<div class="col-12 p-3 border">
                        <p class="h6 text-secondary m-0">
                            آدرس داروخانه :
                            <span class="text-dark fw-bolder">
                                تهران، سعادت آباد
                            </span>
                        </p>
                    </div>*@
                    <div class="col-12 text-center p-3 border">
                        <a href=""
                           class="text-a fw-bolder d-flex align-items-center justify-content-center">
                            <i class="bi bi-pen d-flex me-2"></i>
                            ویرایش اطلاعات
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

VisitOnline/Views/Panel/RequestVisit.cshtml
@model VisitOnline.Models.RequestVisitModel
@using VisitOnline.Services
@inject PanelLayoutScope scope
@{
    ViewData["Title"] = "RequestVisit";
    Layout = "~/Views/Shared/_PanelSickLayout.cshtml";
    string NoshkheNumber = scope.RandomCodeNoskhe();
}

<div class="col-xl-9 col-lg-8 col-md-7 p-2">
    <div class="card border-0 rounded-custom-2 shadow-sm p-3 h-100">
        <div class="col-sm-12 p-2">
            <p class="h2 ismb text-b d-flex align-items-center justify-content-between">
                ارسال درخواست ویزیت به پزشک
                <i class="bi bi-pen"></i>
            </p>
            <hr class="my-2">
        </div>
        <div class="py-3">
            <div class="col-xxl-10 m-auto p-1">
                <form asp-action="RequestVisit" class="m-0">
                    <div class="row w-100 m-0">
                        <div class="col-lg-6 col-md-12 col-sm-6 p-2">
                            <div class="">
                                <label id="numberNoskhe" for="input1" class="form-label">
                                    شماره نسخه : <span id="nn">@NoshkheNumber</span>
                                </label>
                               
                            </div>
                        </div>
                        <div class="col-lg-6 col-md-12 col-sm-6 p-2">
                            <div class="">
                                <label asp-for="Title" for="input1" class="form-label">
                                    عنوان بیماری
                                </label>
                                <input type="text" asp-for="Title" class="form-control rounded-custom-2 text-start" id="input1" placeholder="موضوع بیماری خود را بنویسید">
                                <span asp-validation-for="Title" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="col-12 p-2">
                            <div class="">
                                <label asp-for="Description" for="input2" class="form-label">
                                    توضیحات در مورد بیماری
                                </label>
                                <textarea asp-for="Description" class="form-control rounded-custom-2" id="textarea1" rows="3" placeholder="توضیحات خود را در مورد بیماریتان را بنویسید"></textarea>
                                <span asp-validation-for="Description" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="col-lg-6 col-md-12 col-sm-6 p-2">
                            <div class="">
                                <label asp-for="SickType" for="input2" class="form-label">
                                    نوع بیماری
                                </label>
                                <select asp-for="SickType" class="form-select rounded-custom-2"
                                        aria-label="Default select example">
                                    <option selected>
                                        نوع بیماری خود را انتخاب کنید
                                    </option>
                                    <option value="1">ارتوپد </option>
                                    <option value="2">قلب عروق</option>
                                    <option value="3">مغز اعصاب</option>
                                    <option value="4">بیماری های عفونی</option>
                                    <option value="5">پوست و مو</option>
                                    <option value="6">چشم</option>
                                    <option value="7">گوش و حلق و بینی</option>
                                    <option value="8">گوارش</option>
                                    <option value="9">تغذیه</option>
                                </select>
                            </div>
                        </div>
                        <div class="col-12 p-2">
                            <div class="bg-light rounded-custom-3 shadow-sm p-1">
                                <div class="row w-100 m-0">
                                    <div class="col-12 p-1">
                                        <p class="h6 text-a my-2 px-2 ismb">
                                            پزشک خود را انتخاب کنید :
                                        </p>
                                    </div>
                                </div>

                                <div class="select-dr">
                                    <div class="table-responsive">
                                        <table class="table table-bordered">
                                            <thead>
                                                <tr>
                                                    <th class="text-center" scope="col">
                                                        #
                                                    </th>
                                                    <th class="text-center" scope="col">
                                                        نام پزشک
                                                    </th>
                                                    <th class="text-center" scope="col">
                                                        تخصص
                                                    </th>
                                                    <th class="text-center" scope="col">
                                                        تلفن مطب
                                                    </th>
                                                    <th class="text-center" scope="col">
                                                        آدرس
                                                    </th>
                                                    <th class="text-center" scope="col">
                                                        امتیاز
                                                    </th>

                                                </tr>
                                            </thead>
                                            <tbody>

                                                <tr id="forTd">
                                                </tr>

                                            </tbody>
                                        </table>
                                    </div>

                                </div>
                            </div>
                        </div>
                    </div>
                    <button type="button" class="btn btn-success w-100 rounded-custom-2" onclick="PostData()">ارسال درخواست</button>
                    @*<div class="modal fade" id="alertModal" tabindex="-1" aria-labelledby="alertModalLabel" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered modal-dialog-scrollable">
                <div class="modal-content shadow rounded-custom-3">
                    <div class="modal-header">
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body">
                        <div class="col-12 p-1">
                            <p class="ismb my-3 h5 text-b text-center">
                                مبلغ ویزیت
                            </p>
                            <p class="ismb my-3 h4 text-a text-center">
                                ۵۰،۰۰۰ تومان
                            </p>
                            <p class="my-3 h6 text-danger text-center">
                                آیا مطمئن هستید؟
                            </p>
                        </div>
                        <div class="col-12 p-2">
                            <a href="" class="btn btn-success rounded-custom-2 w-100">
                                پرداخت و ارسال درخواست به پزشک
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>*@
                </form>
            </div>
        </div>
    </div>
</div>
			
@section Scripts 
{

<script>
    var list = [];
    var closestTr = ""
    var idSelectBox= ""
    $("select").change(function () {
         idSelectBox = $(this).find(":selected").val();
       
        
        $.ajax({
            type: 'GET',
            url: "/Panel/GetDoctor/" + idSelectBox,
            data: {} , 

        }).done(function (res) {

            list.push(res);
            console.log(list)
            list.forEach(function (item) {
                
                for (var i = 1; i <= item.length; i++) {
                    $('#forTd').append('<th id="' + item[i - 1].doctorId + ' " class="text - center" name="ac" scope="row"><input asp-for="SelectDoctor" class="form-check-input" type="checkbox" value="" id="checkbox1" /></th > ');
                    $('#forTd').append(' <td class="text-center text-secondary">' + item[i-1].nameFamily + '</td > ')
                    $('#forTd').append(' <td class="text-center text-secondary">' + item[i-1].takhasos + '</td > ')
                    $('#forTd').append(' <td class="text-center text-secondary">' + item[i-1].telMatab + '</td > ')
                    $('#forTd').append(' <td class="text-center text-secondary">' + item[i-1].addressMatab + '</td > ')
                    $('#forTd').append(' <td class="text-center text-secondary">' + item[i - 1].rate + '</td > ')

                 $("#checkbox1").click(function(){
                  closestTr  = $(':checkbox:checked').closest('th').attr('id');
                    alert(closestTr);
                });
                }
                
          
            })
            

        })

      
    });
       

    function PostData() {
        event.preventDefault();
        var desc = $("#textarea1").val();
        var nNoskhe = $("#nn").text();
        var title = $("#input1").val();
        var jsondata = {
            "Title": title, "NumberNoskhe": nNoskhe, "Status": desc, "SickType": idSelectBox, "SelectDoctor": closestTr
        }
        console.log(jsondata)

        $.ajax({
            type: 'POST',
            url: "/Panel/RequestVisit",
            data: jsondata,
        }).done(function (res) {

        })
    }
  
</script>

}
 